baseURL = "https://minhquangzxy.github.io/my-blog/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Minh Quang"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[[params.socialIcons]]
icon = "fa-brands fa-facebook"
title = "e-mail"
url = "https://www.facebook.com/iamquangg.2004"

[[params.socialIcons]]
icon = "fa-brands fa-instagram"
title = "instagram"
url = "https://www.instagram.com/icy.noah_/"


[[params.socialIcons]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/quangphamit/"

[[params.socialIcons]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/minhquangzxy"


[[params.socialIcons]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "mailto:quangptm.it@gmail.com"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=false

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[services]
# Enable Disqus.Disqus.Shortname
  [services.disqus]
    #shortname = 'your-disqus-shortname'
# Google Analytics
  [services.googleAnalytics]
    #ID = 'G-MEASUREMENT_ID'
